version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "c-ecomapp"  # Replace with your S3 bucket
    ARTIFACT_PATH: "eapp/"       # Optional: S3 key prefix
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Starting pre-build...
      - mvn --version

  build:
    commands:
      - echo Building the Java package...
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build complete.
      - echo Checking for WAR file...
      - |
        ARTIFACT_FILE=$(find target -name "*.war" | head -n 1)
        if [ -z "$ARTIFACT_FILE" ]; then
          echo "❌ ERROR: No WAR file generated. Build failed."
          exit 1
        fi
        echo "Found WAR file: $ARTIFACT_FILE"

artifacts:
  files:
    - target/*.war
  discard-paths: yes






